#!/bin/bash

MYSQL='which mysql'

$MYSQL -u root -p -e "$SQL"


Q1="CREATE DATABASE IF NOT EXISTS $1;"
Q2="GRANT ALL ON *.* TO '$2'@'localhost' IDENTIFIED BY '$3';"
Q3="FLUSH PRIVELEGES;"
Q4="${Q1}${Q2}${Q3}"
